Repository COSC481W-2023Fall/nestdoor-app, pull requests merged in 2023-11, with the labels that each got.

#61 style: Improve style and accessibility of Homepage
  src/.gitignore
  src/nestdoorapp/static/css/homepage.css
  src/nestdoorapp/templates/homepage.html
  src/nestdoorapp/templates/registration/login.html
  src/static/css/homepage.css
  src/static/homepage.css
Labels: Sprint2, polishing

#62 style: Improve style and add content to About page
  src/nestdoorapp/static/css/about.css
  src/nestdoorapp/static/css/homepage.css
  src/nestdoorapp/templates/about.html
Labels: Sprint2, polishing

#63 feat: Added User detailed post page for post content
  src/db.sqlite3
  src/functional_tests/test_user_detailed_post.py
  src/nestdoor/urls.py
  src/nestdoorapp/admin.py
  src/nestdoorapp/migrations/0001_initial.py
  src/nestdoorapp/models.py
  src/nestdoorapp/static/css/userpost.css
  src/nestdoorapp/templates/userpost.html
  src/nestdoorapp/urls.py
  src/nestdoorapp/views.py
Labels: enhancement, Sprint2, testing, polishing

#64 fix: Update 'post_id' in 'views.py'
  src/nestdoorapp/views.py
Labels: bug, Sprint2

#72 Delete src/db.sqlite3
  src/db.sqlite3
Labels: bug, Sprint2

#67 Feat: Functional forumn page.
  .gitignore
  src/nestdoorapp/admin.py
  src/nestdoorapp/forms.py
  src/nestdoorapp/migrations/0001_initial.py
  src/nestdoorapp/models.py
  src/nestdoorapp/templates/forum.html
  src/nestdoorapp/templates/userpost.html
  src/nestdoorapp/views.py
Labels: enhancement, Sprint2

#76 Katie routing username to profile
  src/nestdoorapp/migrations/0003_userext.py
  src/nestdoorapp/static/css/userpost.css
  src/nestdoorapp/templates/forum.html
  src/nestdoorapp/templates/homepage.html
  src/nestdoorapp/templates/userpost.html
Labels: enhancement, Sprint2, polishing

#73 Post Editing
  src/nestdoorapp/templates/forum.html
  src/nestdoorapp/templates/post_edit.html
  src/nestdoorapp/templates/userpost.html
  src/nestdoorapp/urls.py
  src/nestdoorapp/views.py
Labels: enhancement, Sprint2

#88 style: Changed the html and CSS files for Top Navigation Bar consistency
  src/nestdoorapp/static/css/homepage.css
  src/nestdoorapp/static/css/userpost.css
  src/nestdoorapp/static/css/userprofile.css
  src/nestdoorapp/templates/about.html
  src/nestdoorapp/templates/bad_user.html
  src/nestdoorapp/templates/forum.html
  src/nestdoorapp/templates/homepage.html
  src/nestdoorapp/templates/post_edit.html
  src/nestdoorapp/templates/userpost.html
  src/nestdoorapp/templates/userprofilepage.html
  src/nestdoorapp/views.py
Labels: Beta Sprint, polishing

#94 Forms.py and Homepage.css edited to make field errors more visible an…
  src/nestdoorapp/forms.py
  src/nestdoorapp/static/css/homepage.css
Labels: enhancement, Beta Sprint, polishing

#95 Style & Fix: Placeholder Text in About Me on Profile Page
  src/nestdoorapp/templates/userprofilepage.html
  src/nestdoorapp/views.py
Labels: enhancement, Beta Sprint, polishing

#98 reed-changed-contrast-for-detailed-post-page
  src/nestdoorapp/static/css/userpost.css
Labels: Beta Sprint, polishing

#97 Add top 3 posts to homepage
  src/nestdoorapp/templates/homepage.html
  src/nestdoorapp/views.py
Labels: enhancement, Beta Sprint
