Repository COSC481W-2023Fall/nestdoor-app, pull requests merged in 2023-10, with the labels that each got.

#18 style: Improve default home page layout and header bar
  src/db.sqlite3
  src/nestdoor/settings.py
  src/nestdoor/urls.py
  src/nestdoorapp/static/css/App.css
  src/nestdoorapp/static/css/homepage.css
  src/nestdoorapp/static/images/logo192.png
  src/nestdoorapp/static/images/logo512.png
  src/nestdoorapp/static/images/reed_logo1.png
  src/nestdoorapp/static/images/reed_logo2.png
  src/nestdoorapp/templates/about.html
  src/nestdoorapp/templates/forum.html
  src/nestdoorapp/templates/homepage.html
  src/nestdoorapp/templates/login.html
  src/nestdoorapp/templates/logout.html
  src/nestdoorapp/urls.py
  src/nestdoorapp/views.py
  src/requirements.txt
  src/templates/base.html
Labels: enhancement, Sprint1

#20 designed-and-added-mini-logo-to-all-pages
  src/db.sqlite3
  src/nestdoor/settings.py
  src/nestdoorapp/static/images/reed_logo_mini.png
  src/nestdoorapp/templates/about.html
  src/nestdoorapp/templates/forum.html
  src/nestdoorapp/templates/homepage.html
  src/nestdoorapp/templates/login.html
  src/nestdoorapp/templates/logout.html
  src/requirements.txt
Labels: enhancement, Sprint1

#28 test: Added tests for home page and header bar
  src/functional_tests/test_default_homepage.py
  src/functional_tests/test_header_bar.py
Labels: Sprint1, testing

#31 Feat-Fix: Check Constraints for Models
  .vs/VSWorkspaceState.json
  .vs/nestdoor-app/FileContentIndex/2f8eef4c-2d65-43d9-a6a6-d8c8a35f8de8.vsidx
  .vs/nestdoor-app/FileContentIndex/671c4823-2b6f-4229-8d5c-6c55275b4630.vsidx
  .vs/nestdoor-app/FileContentIndex/7731dc14-9e4e-4b82-923e-d5106a9308dc.vsidx
  .vs/nestdoor-app/FileContentIndex/90e3d869-e8b3-4476-85cc-abd77c95d62f.vsidx
  .vs/nestdoor-app/FileContentIndex/9d27542e-fc7c-4b7e-94e7-abf3d422a6d5.vsidx
  .vs/nestdoor-app/FileContentIndex/bdf56ad0-ce3b-4505-91ab-028c4ee87a14.vsidx
  .vs/nestdoor-app/FileContentIndex/be0cb646-ec6e-42bb-88b5-aa95fba43879.vsidx
  .vs/nestdoor-app/v17/.wsuo
  .vs/nestdoor-app/v17/workspaceFileList.bin
  .vs/slnx.sqlite
  src/nestdoor/settings.py
  src/nestdoorapp/models.py
Labels: Sprint1

#38 Added homepage background, test on hovering. Modified hovering effect on Logos
  src/functional_tests/test_hover_on_icon.py
  src/nestdoorapp/static/css/homepage.css
  src/nestdoorapp/templates/about.html
  src/nestdoorapp/templates/forum.html
  src/nestdoorapp/templates/homepage.html
Labels: enhancement, Sprint1

#46 fix: Fixed top navigation bar in homepage.css so content is not blocked
  src/nestdoorapp/static/css/homepage.css
  src/nestdoorapp/templates/homepage.html
Labels: bug, Sprint2
